name: Fetch Latest Hashnode Blog Posts

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # Grant write permission to the repository contents

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch Hashnode Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
          comment_tag_name: "HASHNODE_BLOG"
          feed_list: "https://thewood.hashnode.dev/rss.xml"
          template: |
              - <a href="$url" target="_blank">$title</a>
          date_format: "mmm dd, yyyy"
          max_post_count: 4
