name: Fetch Latest Hashnode Blog Posts

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # Grant write permission to the repository contents

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch Hashnode Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
          comment_tag_name: "HASHNODE_BLOG"
          feed_list: "https://thewood.hashnode.dev/rss.xml"
          template: |
            <tr>
              <td style="padding: 10px; text-align: center;">
                <a href="$url" style="text-decoration: none;">
                  <img src="$image" alt="$title" width="100%" style="border-radius: 8px;"/>
                </a>
              </td>
              <td style="padding: 10px; font-family: Arial, sans-serif;">
                <a href="$url" style="text-decoration: none; color: #2d3748; font-size: 18px; font-weight: bold;">
                  $title
                </a>
                <br>
                <em style="color: #718096;">Published on $date</em>
                <br><br>
                <span style="color: #4a5568;">$description</span>
              </td>
            </tr>
          date_format: "mmm dd, yyyy"
          max_post_count: 4
